# Generated by Django 3.0.8 on 2020-08-25 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batterie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomebatterie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('operation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Barile',
            fields=[
                ('nomeb', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('capacita', models.IntegerField()),
                ('tipolegno', models.CharField(max_length=20)),
                ('bat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shushan1.Batterie')),
            ],
        ),
    ]
