# Generated by Django 3.0.8 on 2020-08-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shushan1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
