# Generated by Django 3.0.8 on 2020-08-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shushan1', '0002_auto_20200825_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
