# Generated by Django 3.0.8 on 2020-08-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shushan1', '0005_info_nomebarile'),
    ]

    operations = [
        migrations.AddField(
            model_name='barile',
            name='capacita_max',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barile',
            name='densita',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barile',
            name='precedente',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barile',
            name='prossimo',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
    ]
