# Generated by Django 3.0.8 on 2020-08-25 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shushan1', '0006_auto_20200825_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barile',
            old_name='capacita_max',
            new_name='capacitamax',
        ),
    ]
