# Generated by Django 3.0.8 on 2020-08-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shushan1', '0007_auto_20200825_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rabbocco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barileorigine', models.CharField(max_length=50)),
                ('bariledestinazione', models.CharField(max_length=50)),
                ('quantita', models.IntegerField()),
            ],
        ),
    ]
